apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
  labels:
    name: ingress
spec:
<<<<<<< HEAD
  tls:
    - secretName: myssl
      hosts:
        - ticketing.bandzior
=======
>>>>>>> a86f298fa862c7ad1f9ab79884353ac000386356
  rules:
    - host: ticketing.bandzior
      http:
        paths:
          - pathType: Prefix
            path: /api/users/?(.*)
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
<<<<<<< HEAD
          - pathType: Prefix
            path: /?(.*)
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller
  namespace: ingress-nginx
data:
  ssl-redirect: 'false'
=======
>>>>>>> a86f298fa862c7ad1f9ab79884353ac000386356
