name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t $DOCKER_USERNAME/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push $DOCKER_USERNAME/expiration
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - run: doctl kubernetes cluster kubeconfig save CLUSTER_NAME
      # - run: kubectl rollout restart deployment expiration-depl
